services:
  app:
    image: node:16
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    ports:
      - 5173:5173
    command: bash -c "npm install && npm run dev -- --host"