version: '3.8'

services:
  nginx:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/bloglist
      - PORT=3003
      - SECRET=${SECRET}
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: